### ISSUE TITLE
[11.0.1] build fails, beause missing GCC option

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-libs#334]
The build fails with:
[ 96%] Built target gvm_base_shared
/builddir/build/BUILD/gvm-libs-11.0.1/util/xmlutils.c: In function 'find_child':
/builddir/build/BUILD/gvm-libs-11.0.1/util/xmlutils.c:1750:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (xmlNode *node = element->children; node; node = node->next)
   ^
/builddir/build/BUILD/gvm-libs-11.0.1/util/xmlutils.c:1750:3: note: use option -std=c99 or -std=gnu99 to compile your code

**Comment by tuxmaster5000** [comment]
Using an newer gcc (9.1.1.) then this line will work without the patch, but later it fails with:

> cd /builddir/build/BUILD/gvm-libs-11.0.1/util && /usr/lib64/ccache/cc -DENABLE_LDAP_AUTH=1 -DENABLE_RADIUS_AUTH=1 -DGVM_LIBS_VERSION=\"11.0.1\" -DNVTICACHE_STR=\"nvticache11.0.1\" -DRADIUS_AUTH_FREERADIUS=1 -DREDIS_SOCKET_PATH=\"/run/redis/redis.sock\" -Dgvm_util_shared_EXPORTS -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gvm-helper -I/usr/include/libxml2  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -D_FILE_OFFSET_BITS=64 -DLARGEFILE_SOURCE=1 -g -Wall -Wextra -Werror  -fPIC   -o CMakeFiles/gvm_util_shared.dir/xmlutils.c.o   -c /builddir/build/BUILD/gvm-libs-11.0.1/util/xmlutils.c
> In file included from /usr/include/string.h:638,
>                  from /usr/include/glib-2.0/glib/gtestutils.h:30,
>                  from /usr/include/glib-2.0/glib.h:82,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/base/settings.h:30,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/base/prefs.c:28:
> In function 'strncpy',
>     inlined from 'prefs_config' at /builddir/build/BUILD/gvm-libs-11.0.1/base/prefs.c:155:3:
> /usr/include/bits/string3.h:120:10: error: '__builtin_strncpy' specified bound 2048 equals destination size [-Werror=stringop-truncation]
>   120 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> make[2]: *** [base/CMakeFiles/gvm_base_shared.dir/build.make:183: base/CMakeFiles/gvm_base_shared.dir/prefs.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/builddir/build/BUILD/gvm-libs-11.0.1'
> make[1]: *** [CMakeFiles/Makefile2:126: base/CMakeFiles/gvm_base_shared.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> In file included from /usr/include/string.h:638,
>                  from /usr/include/glib-2.0/glib/gtestutils.h:30,
>                  from /usr/include/glib-2.0/glib.h:82,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/../base/nvti.h:30,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.h:28,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:27:
> In function 'strncpy',
>     inlined from 'redis_direct_conn' at /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:429:3:
> /usr/include/bits/string3.h:120:10: error: '__builtin_strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
>   120 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c: In function 'redis_direct_conn':
> /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:429:3: note: length computed here
>   429 |   strncpy (kbr->path, kb_path, strlen (kb_path));
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/string.h:638,
>                  from /usr/include/glib-2.0/glib/gtestutils.h:30,
>                  from /usr/include/glib-2.0/glib.h:82,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/../base/nvti.h:30,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.h:28,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:27:
> In function 'strncpy',
>     inlined from 'redis_new' at /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:396:3:
> /usr/include/bits/string3.h:120:10: error: '__builtin_strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
>   120 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c: In function 'redis_new':
> /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:396:3: note: length computed here
>   396 |   strncpy (kbr->path, kb_path, strlen (kb_path));
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/string.h:638,
>                  from /usr/include/glib-2.0/glib/gtestutils.h:30,
>                  from /usr/include/glib-2.0/glib.h:82,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/../base/nvti.h:30,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.h:28,
>                  from /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:27:
> In function 'strncpy',
>     inlined from 'redis_find' at /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:471:3:
> /usr/include/bits/string3.h:120:10: error: '__builtin_strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
>   120 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c: In function 'redis_find':
> /builddir/build/BUILD/gvm-libs-11.0.1/util/kb.c:471:3: note: length computed here
>   471 |   strncpy (kbr->path, kb_path, strlen (kb_path));
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> make[2]: Leaving directory '/builddir/build/BUILD/gvm-libs-11.0.1'
> make[1]: Leaving directory '/builddir/build/BUILD/gvm-libs-11.0.1'
> 
> 
> RPM build errors:
> make[2]: *** [util/CMakeFiles/gvm_util_shared.dir/build.make:118: util/CMakeFiles/gvm_util_shared.dir/kb.c.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:181: util/CMakeFiles/gvm_util_shared.dir/all] Error 2

**Comment by tuxmaster5000** [comment]
So with this patch it will work with gcc up to 6.3.0.

**Comment by bjoernricks** [comment]
Fixed with https://github.com/greenbone/gvm-libs/pull/335
