### ISSUE TITLE
gvm-libs release branch will not compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by asmaack** [greenbone/gvm-libs#129]
### Expected behavior
Normal build process

### Current behavior
git checkout release branch or tag and make failes at gvm-libs/nasl/nasl_isotime.c
Do a "git checkout master" and build process will finish normally.

### Steps to reproduce
Using git clone and checking out release tag or branch:

```
~$ git clone https://github.com/greenbone/gvm-libs.git
~/gvm-libs$ git checkout tags/v9.0.3 (or "git checkout openvas-libraries-9.0")
Note: checking out 'tags/v9.0.3'.
HEAD is now at c32cbc91

~/gvm-libs$ mkdir build
~/gvm-libs$ cd build
~/gvm-libs/build$ cmake ..
~/gvm-libs/build$ make
Scanning dependencies of target openvas_base_shared
[  1%] Building C object base/CMakeFiles/openvas_base_shared.dir/array.c.o
[  2%] Building C object base/CMakeFiles/openvas_base_shared.dir/credentials.c.o
.
.
[ 84%] Building C object nasl/CMakeFiles/openvas_nasl_shared.dir/nasl_isotime.c.o
/home/asgeir/gvm-libs/nasl/nasl_isotime.c: In function ‘add_years_to_isotime’:
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:561:52: error: ‘%02d’ directive output may be truncated writing between 2 and 5 bytes into a region of size between 0 and 5 [-Werror=format-truncation=]
   snprintf (atime, ISOTIME_SIZE, "%04d%02d%02dT%02d%02d%02d",
                                                    ^~~~
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:561:34: note: directive argument in the range [-1936, 869]
   snprintf (atime, ISOTIME_SIZE, "%04d%02d%02dT%02d%02d%02d",
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:561:34: note: directive argument in the range [-1936, 869]
In file included from /usr/include/stdio.h:862:0,
                 from /home/asgeir/gvm-libs/nasl/nasl_isotime.c:54:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 16 and 50 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/asgeir/gvm-libs/nasl/nasl_isotime.c: In function ‘nasl_isotime_add’:
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:522:52: error: ‘%02d’ directive output may be truncated writing between 2 and 5 bytes into a region of size between 0 and 5 [-Werror=format-truncation=]
   snprintf (atime, ISOTIME_SIZE, "%04d%02d%02dT%02d%02d%02d",
                                                    ^~~~
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:522:34: note: directive argument in the range [-1936, 869]
   snprintf (atime, ISOTIME_SIZE, "%04d%02d%02dT%02d%02d%02d",
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:522:34: note: directive argument in the range [-1936, 869]
In file included from /usr/include/stdio.h:862:0,
                 from /home/asgeir/gvm-libs/nasl/nasl_isotime.c:54:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 16 and 50 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:483:56: error: ‘%02d’ directive output may be truncated writing between 2 and 3 bytes into a region of size between 0 and 3 [-Werror=format-truncation=]
   snprintf (atime, ISOTIME_SIZE, "%04d%02d%02dT%02d%02d%02d",
                                                        ^~~~
/home/asgeir/gvm-libs/nasl/nasl_isotime.c:483:34: note: directive argument in the range [-59, 59]
   snprintf (atime, ISOTIME_SIZE, "%04d%02d%02dT%02d%02d%02d",
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /home/asgeir/gvm-libs/nasl/nasl_isotime.c:54:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 16 and 44 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
nasl/CMakeFiles/openvas_nasl_shared.dir/build.make:1056: recipe for target 'nasl/CMakeFiles/openvas_nasl_shared.dir/nasl_isotime.c.o' failed
make[2]: *** [nasl/CMakeFiles/openvas_nasl_shared.dir/nasl_isotime.c.o] Error 1
CMakeFiles/Makefile2:344: recipe for target 'nasl/CMakeFiles/openvas_nasl_shared.dir/all' failed
make[1]: *** [nasl/CMakeFiles/openvas_nasl_shared.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

### Environment
**Operating system:**
$ uname -a
Linux xxx 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Installation method / source:** 
(source installation)

**Comment by kroosec** [comment]
Thanks for reporting this. Fixed in https://github.com/greenbone/gvm-libs/pull/130

**Comment by asmaack** [comment]
Does this fix go into the release bransh (openvas-libraries-9.0), or should I stick with the master branch?

**Comment by kroosec** [comment]
> Does this fix go into the release bransh (openvas-libraries-9.0), or should I stick with the master branch?

Master branch is not affected afaict. Fix is for openvas-9.
