### ISSUE TITLE
22.35.7: build failure with glibc 2.43

### ISSUE THREAD

**Issue by tgurr** [greenbone/gvm-libs#1051]
### Expected behavior
Do not fail to build with glibc 2.43.

### Actual behavior
```
[...]
[ 40%] Building C object util/CMakeFiles/gvm_util_shared.dir/kb.c.o
cd /var/tmp/paludis/build/net-analyzer-gvm-libs-22.35.7/work/build/util && /usr/bin/x86_64-pc-linux-gnu-cc -DENABLE_LDAP_AUTH=1 -DGVM_LIBS_VERSION=\"22.35.7\" -DHAVE_MQTT=1 -DREDIS_SOCKET_PATH=\"/tmp/redis.sock\" -Dgvm_util_shared_EXPORTS -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include -I/usr/x86_64-pc-linux-gnu/include/libxml2 -pipe -O2 -march=native      -std=c11     -Wall     -Wextra     -Werror     -Wpedantic     -Wmissing-prototypes     -Wshadow     -Wsequence-point     -D_ISOC11_SOURCE     -D_DEFAULT_SOURCE -O3 -DNDEBUG -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector  -std=gnu11 -fPIC -fdiagnostics-color=always -MD -MT util/CMakeFiles/gvm_util_shared.dir/kb.c.o -MF CMakeFiles/gvm_util_shared.dir/kb.c.o.d -o CMakeFiles/gvm_util_shared.dir/kb.c.o -c /var/tmp/paludis/build/net-analyzer-gvm-libs-22.35.7/work/gvm-libs-22.35.7/util/kb.c
/var/tmp/paludis/build/net-analyzer-gvm-libs-22.35.7/work/gvm-libs-22.35.7/util/kb.c: In function 'parse_port_of_addr':
/var/tmp/paludis/build/net-analyzer-gvm-libs-22.35.7/work/gvm-libs-22.35.7/util/kb.c:254:7: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  254 |   tmp = strrchr (addr + tcp_indicator_len, ':');
      |
```

See: https://sourceware.org/glibc/wiki/Release/2.43#C23_Const-Preserving_Standard_Library_Macros_May_Break_Some_Packages

### Steps to reproduce
1. install/upgrade to glibc 2.43
2. try to build gvm-libs 22.35.7

### Environment
**GCC**: 14.3.0
**Operating system:** Exherbo Linux
**Installation method / source:** source-based packages

### Logfiles
Complete build log: [gvm-libs-22.35.7_build.log](https://github.com/user-attachments/files/25432333/gvm-libs-22.35.7_build.log)
